title: Website Title

description: >
  Website Description

author:
  name: Name
  email: your-email@domain.com

collections:
  components:
    output: true
    permalink: /:collection/:path/

nav_pages:
  - about.md
  - components.md

max-width: 800px

show_excerpts: true
show_rss_feed: true
show_github_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

content_selector: div.post-content,div.home
