title: Juncture IFC

description: >
  Juncture Iframe Components.

author:
  name: Ron Snyder
  email: ron@snyderjr.com

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  docs:
    output: true
    permalink: /:collection/:path/
  examples:
    output: true
    permalink: /:collection/:path/
  components:
    output: true
    permalink: /:collection/:path/

nav_pages:
  - _pages/about.md
  - _pages/docs.md
  - _pages/examples.md
  - _pages/blog.md

max-width: 1000px

show_excerpts: true
show_rss_feed: true
show_github_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
